import React from 'react';
import { Link } from 'react-router-dom';
import { FiHeart, FiMapPin, FiMail, FiPhone } from 'react-icons/fi';
import styles from './Footer.module.css';

function Footer() {
  return (
    <footer className={styles.footer}>
      <div className="container">
        <div className={styles.grid}>
          {/* Brand & Mission */}
          <div className={styles.brandCol}>
            <Link className={styles.brand} to="/">
              <span className={styles.brandMark}>+</span>
              <span className={styles.brandText}>CarePlus</span>
            </Link>
            <p className={styles.brandDesc}>
              A premium AI-powered patient assistant designed to triage symptoms, recommend Indian specialty clinics, and schedule doctor visits effortlessly.
            </p>
          </div>

          {/* Quick Links */}
          <div className={styles.linksCol}>
            <h4 className={styles.colTitle}>Care Modules</h4>
            <ul className={styles.list}>
              <li><Link to="/symptom-checker">AI Symptom Triage</Link></li>
              <li><Link to="/hospitals">Hospital Discovery</Link></li>
              <li><Link to="/appointments">Doctor Consultations</Link></li>
              <li><Link to="/dashboard">Personal Dashboard</Link></li>
            </ul>
          </div>

          {/* About & Support */}
          <div className={styles.linksCol}>
            <h4 className={styles.colTitle}>Support</h4>
            <ul className={styles.list}>
              <li><Link to="/about">About CarePlus Project</Link></li>
              <li style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}><FiMapPin size={14} /> <span>New Delhi, India</span></li>
              <li style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}><FiMail size={14} /> <span>support@careplus.example</span></li>
              <li style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}><FiPhone size={14} /> <span>+91-11-2692-5858</span></li>
            </ul>
          </div>
        </div>

        {/* Bottom band with disclaimer */}
        <div className={styles.bottomBand}>
          <p className={styles.disclaimer}>
            <strong>Clinical Warning & Disclaimer:</strong> CarePlus is a simulated patient care system. The symptoms, conditions, and recommendations generated by the AI model are for reference purposes only and do not replace professional medical opinions, diagnostic testing, or clinical consultations. In case of emergency, please visit a local hospital immediately.
          </p>
          <div className={styles.copyRow}>
            <span>&copy; {new Date().getFullYear()} CarePlus Inc. Built with React & Framer Motion.</span>
            <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.35rem' }}>
              Made with <FiHeart fill="#EF4444" color="#EF4444" size={12} /> for healthy lives.
            </span>
          </div>
        </div>
      </div>
    </footer>
  );
}

export default Footer;
